- hosts: '192.168.0.106'
  vars_files: 'datanode_var.yml'
  tasks:
    - name: 'copying hadoop file to target node'
      copy:
        src: '/root/hadoop-1.2.1-1.x86_64.rpm'
        dest: '/root/'

    - name: 'copying jdk file to target node '
      copy:
        src: '/root/jdk-8u171-linux-x64.rpm'
        dest: '/root/'

    - name: 'installing hadoop'
      command:
        cmd: 'rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force'
        warn: no

    - name: 'installing jdk'
      command:
        cmd: 'rpm -i /root/jdk-8u171-linux-x64.rpm'

    - name: 'copying hdfs and core on Datanode'
      vars:
        node: 'data'
        master_ip: '192.168.0.103'

      block:
        - template:
            src: '/etc/ansible/master/hdfs-site.xml'
            dest: '/etc/hadoop/'
        - template:
            src: '/etc/ansible/master/core-site.xml'
            dest: '/etc/hadoop/'

      when: ansible_facts["default_ipv4"]["address"] == ip_for_checking

    - name: 'starting datanode'
      command:
        cmd: 'hadoop-daemon.sh start datanode'
      
 

